#!/bin/bash

OUTPUT_DIR="${1:-.}"
OUTPUT_FILE="$OUTPUT_DIR/troc"
VERSION=$(git describe --tags)

echo "Building troc version $VERSION executable at $OUTPUT_FILE"

LDFLAGS="-X 'cmd.root.version=$VERSION'"
go build -o $OUTPUT_FILE -ldflags="$LDFLAGS" main.go
