#!/bin/bash

OUTPUT_DIR="${1:-.}"
OUTPUT_FILE="$OUTPUT_DIR/troc"
VERSION=$(git describe --tags)

echo "Building troc version $VERSION executable at $OUTPUT_FILE"

# Use `go tool nm` to find this
LDFLAGS="-X 'github.com/samcarswell/trochilus/cmd.version=$VERSION'"
go build -o $OUTPUT_FILE -ldflags="$LDFLAGS" main.go
