// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"database/sql"
	"time"
)

type Cron struct {
	ID   int64
	Name string
}

type Run struct {
	ID          int64
	CronID      int64
	StartTime   time.Time
	EndTime     sql.NullTime
	LogFile     string
	ExecLogFile string
	Succeeded   bool
}
