// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"database/sql"
	"time"
)

type Job struct {
	ID               int64
	Name             string
	NotifyLogContent bool
}

type Run struct {
	ID          int64
	JobID       int64
	StartTime   time.Time
	EndTime     sql.NullTime
	LogFile     string
	ExecLogFile string
	Status      string
}
