// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package data

import (
	"context"
)

const createCron = `-- name: CreateCron :one
insert into crons
    (name)
values (?)
returning id
`

func (q *Queries) CreateCron(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCron, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const endRun = `-- name: EndRun :exec
update runs
set end_time = current_timestamp, succeeded = ?
where id = ?
`

type EndRunParams struct {
	Succeeded bool
	ID        int64
}

func (q *Queries) EndRun(ctx context.Context, arg EndRunParams) error {
	_, err := q.db.ExecContext(ctx, endRun, arg.Succeeded, arg.ID)
	return err
}

const getCron = `-- name: GetCron :one
select
    crons.id, crons.name
from crons
where crons.name = ?
`

type GetCronRow struct {
	Cron Cron
}

func (q *Queries) GetCron(ctx context.Context, name string) (GetCronRow, error) {
	row := q.db.QueryRowContext(ctx, getCron, name)
	var i GetCronRow
	err := row.Scan(&i.Cron.ID, &i.Cron.Name)
	return i, err
}

const getCrons = `-- name: GetCrons :many
select
    crons.id, crons.name
from crons
`

type GetCronsRow struct {
	Cron Cron
}

func (q *Queries) GetCrons(ctx context.Context) ([]GetCronsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCrons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCronsRow
	for rows.Next() {
		var i GetCronsRow
		if err := rows.Scan(&i.Cron.ID, &i.Cron.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
select
    runs.id, runs.cron_id, runs.start_time, runs.end_time, runs.stdout_log_file, runs.stderr_log_file, runs.exec_log_file, runs.succeeded,
    crons.id, crons.name
from runs, crons
where runs.cron_id = crons.id
and runs.id = ?
`

type GetRunRow struct {
	Run  Run
	Cron Cron
}

func (q *Queries) GetRun(ctx context.Context, id int64) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.Run.ID,
		&i.Run.CronID,
		&i.Run.StartTime,
		&i.Run.EndTime,
		&i.Run.StdoutLogFile,
		&i.Run.StderrLogFile,
		&i.Run.ExecLogFile,
		&i.Run.Succeeded,
		&i.Cron.ID,
		&i.Cron.Name,
	)
	return i, err
}

const getRuns = `-- name: GetRuns :many
select
    runs.id, runs.cron_id, runs.start_time, runs.end_time, runs.stdout_log_file, runs.stderr_log_file, runs.exec_log_file, runs.succeeded,
    crons.id, crons.name
from runs, crons
where runs.cron_id = crons.id
`

type GetRunsRow struct {
	Run  Run
	Cron Cron
}

func (q *Queries) GetRuns(ctx context.Context) ([]GetRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRunsRow
	for rows.Next() {
		var i GetRunsRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.CronID,
			&i.Run.StartTime,
			&i.Run.EndTime,
			&i.Run.StdoutLogFile,
			&i.Run.StderrLogFile,
			&i.Run.ExecLogFile,
			&i.Run.Succeeded,
			&i.Cron.ID,
			&i.Cron.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isRunFinished = `-- name: IsRunFinished :one
select runs.end_time is not null
from runs
where runs.id = ?
`

func (q *Queries) IsRunFinished(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRunFinished, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const startRun = `-- name: StartRun :one
insert into runs
    (cron_id, start_time, stdout_log_file, stderr_log_file, exec_log_file)
values (?, current_timestamp, ?, ?, ?)
returning id
`

type StartRunParams struct {
	CronID        int64
	StdoutLogFile string
	StderrLogFile string
	ExecLogFile   string
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, startRun,
		arg.CronID,
		arg.StdoutLogFile,
		arg.StderrLogFile,
		arg.ExecLogFile,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
